# Site settings
title: DKP Cottbus
baseurl: "" 
url: # the base hostname & protocol for your site

# SEO
description: 
author: Fabian Große
facebook:
  publisher: 
logo: 
lang: de_DE

# Analytics
google-analytics:

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - _posts/_template.md
